=== Резюме

В этой главе мы рассмотрели много нативных концепций Rust! Теперь, когда вы знаете о параметрах обобщенного типа, трейтах и баундах, а также обобщенных параметрах времени жизни, то готовы писать код без повторений, который работает во многих различных ситуациях. Параметры обобщенного типа позволяют применять код к различным типам. Трейты и баунды гарантируют, что даже если типы являются обобщенными, они будут иметь поведение, необходимое вашему коду. Теперь вы знаете, как использовать аннотации времени жизни, чтобы гарантировать в этом гибком коде отсутствие висячих ссылок. И весь этот анализ происходит во время компиляции, не оказывая никакого влияния на производительность во время выполнения!

Но мы лишь затронули эти темы очень поверхностно, о них можно узнать гораздо больше, например, в Главе 17 обсуждаются трейт-объекты, которые представляют собой еще один способ использования трейтов. Существуют также более сложные сценарии, включающие аннотации времени жизни, которые понадобятся только в очень сложных случаях; до знакомства с ними вам следует прочитать документацию "Rust Reference" по ссылке _https://doc.rust-lang.org/reference/index.html_. А сейчас пришло время узнать, как писать тесты на Rust, чтобы убедиться, что ваш код работает должным образом.
