[#_10_1_generic_data_types]
=== 10.1. Обобщенные типы данных

Обобщенные типы применяются для создания определений таких элементов, как сигнатуры функций или структуры, которые можно использовать со многими различными конкретными типами данных. Давайте сначала посмотрим, как определять функции, структуры, перечисления и методы с помощью обобщенных типов. Затем обсудим, как обобщенные типы влияют на производительность кода.

==== В определениях функций

Обобщенные типы указываются в сигнатуре функции на местах, в которых обычно размещаются типы данных параметров и возвращаемых значений. Такой синтаксис повышает гибкость кода и предоставляет больше возможностей вызывающим функциям, избегая при этом дублирования программ.

В листинге 10-4 показаны две новые функции, написанные на основе функции `largest` и которые находят наибольшее значение в срезе заданного конкретного типа. Затем мы объединим их в одну функцию, использующую обобщенный тип.

--
.Листинг 10-4: Две функции с одинаковым поведением, которые отличаются только именами и типами в своих сигнатурах.

Файл: src/main.rs

[source,rust]
----
fn largest_i32(list: &[i32]) -> &i32 {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn largest_char(list: &[char]) -> &char {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let result = largest_i32(&number_list);
    println!("The largest number is {}", result);
    assert_eq!(*result, 100);

    let char_list = vec!['y', 'm', 'a', 'q'];

    let result = largest_char(&char_list);
    println!("The largest char is {}", result);
    assert_eq!(*result, 'y');
}
----
--

Функцию `largest_i32` мы взяли из листинга 10-3. Она находит наибольший `i32` в срезе вектора целых чисел. Функция `largest_char` также взята из листинга 10-3 и находит наибольший `char` в срезе вектора символов. Тела функций имеют одинаковый код, поэтому давайте устраним дублирование, определив одну обобщенную функцию с параметром обобщенного типа.

Чтобы параметризовать типы в новой отдельной функции, нам нужно назвать параметр типа так же, как мы делаем это для обычных параметров функции. В качестве имени параметра типа можно использовать любой допустимый идентификатор Rust. Но у нас параметр будет называться `T`, потому что по принятому соглашению в Rust для параметров обобщенного типа применяются короткие имена, часто просто буквы, причем в нотации CamelCase. `T` как сокращение от «type» — это выбор большинства программистов Rust по умолчанию.

Когда мы используем параметр в теле функции, то должны объявить имя параметра в сигнатуре, чтобы компилятор знал, что означает это имя. Точно так же, в случае применения обобщенного типа в сигнатуре функции, нужно объявить имя параметра этого типа перед его использованием. Чтобы определить функцию `largest` с обобщенным типом, или другими словами _обобщенную функцию_, поместите объявление имени типа в угловые скобки `<>` между именем функции и списком параметров:

[source,rust]
----
fn largest<T>(list: &[T]) -> &T {
----

Это определение читается так: функция `largest` является обобщенной функцией для некоторого типа `T`. Эта функция имеет один параметр с именем `list`, который представляет собой срез значений типа `T` и возвращает ссылку на значение того же типа `T`.

В листинге 10-5 показано комбинированное определение функции `largest`, использующее обобщенный тип данных в своей сигнатуре. В листинге также показано, как мы можем вызывать функцию со срезом значений `i32`, или значений `char`. Заметим, что этот код пока не компилируется, но мы исправим это позже в этой главе.

--
.Листинг 10-5: Функция `largest` с параметром обобщенного типа (код не компилируется)

Файл: src/main.rs

[source,rust]
----
fn largest<T>(list: &[T]) -> &T {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let result = largest(&number_list);
    println!("The largest number is {}", result);

    let char_list = vec!['y', 'm', 'a', 'q'];

    let result = largest(&char_list);
    println!("The largest char is {}", result);
}
----
--

При попытке компиляции получим такую ошибку:

[example]
----
$ cargo run
   Compiling chapter10 v0.1.0 (file:///projects/chapter10)
error[E0369]: binary operation `>` cannot be applied to type `&T`
 --> src/main.rs:5:17
  |
5 |         if item > largest {
  |            ---- ^ ------- &T
  |            |
  |            &T
  |
help: consider restricting type parameter `T`
  |
1 | fn largest<T: std::cmp::PartialOrd>(list: &[T]) -> &T {
  |             ++++++++++++++++++++++

For more information about this error, try `rustc --explain E0369`.
error: could not compile `chapter10` due to previous error
----

В тексте подсказки упоминается `std::cmp::PartialOrd` - это _трейт_, о которых поговорим в следующем разделе. Ошибка означает, что функция не будет работать для всех возможных типов, которыми может быть `T`. Поскольку требуется сравнивать значения типа `T`, мы можем использовать только те типы, значения которых могут быть упорядочены. Для разрешения сравнений как раз и применяется трейт `std::cmp::PartialOrd`, определенный в стандартной библиотеке (дополнительные сведения об этом трейте см. в Приложении C). Следуя предложению в тексте ошибки, мы можем ограничить типы, допустимые для `T`, только теми, которые реализуют указанный трейт. Так как в стандартной библиотеке есть реализация `PartialOrd` как для `i32`, так и для `char`, код будет успешно компилироваться.

==== В определениях структур

Применяя синтаксис `<>`, можно определить обобщенную структуру с указанием параметра обобщенного типа в одном или нескольких ее полях. В листинге 10-6 определяется обобщенная структура `Point<T>` для хранения значений координат `x` и `y` любого типа.

--
.Листинг 10-6: Структура Point<T>, содержащая значения x и y типа T

Файл: src/main.rs

[source,rust]
----
struct Point<T> {
    x: T,
    y: T,
}

fn main() {
    let integer = Point { x: 5, y: 10 };
    let float = Point { x: 1.0, y: 4.0 };
}
----
--

Синтаксис обобщенных типов в определениях структур ничем не отличается от функций. Сначала мы объявляем имя параметра обобщенного типа в угловых скобках сразу после имени структуры. Затем мы используем этот параметр в определении структуры там, где в обычной ситуации указывали бы конкретные типы данных.

Заметим, что обобщенный тип для определения `Point<T>` только один, в этом определении говорится, что структура `Point<T>` является обобщенной для некоторого типа `T`, а _оба_ поля `x` и `y` относятся к _одному и тому же_ типу, независимо от того, каким может быть этот тип. Если мы создадим экземпляр `Point<T>` со значениями разных типов, как в листинге 10-7, наш код не скомпилируется.

--
.Листинг 10-7: Поля x и y должны быть одного типа, потому что оба имеют одинаковый тип данных T

Файл: src/main.rs

[source,rust]
----
struct Point<T> {
    x: T,
    y: T,
}

fn main() {
    let wont_work = Point { x: 5, y: 4.0 };
}
----
--

В этом примере, когда мы присваиваем полю `x` целочисленное значение 5, то сообщаем компилятору, что тип `T` будет целым числом для этого экземпляра `Point<T>`. Затем, когда указываем 4.0 (значение типа f64) для поля `y`, которое по определению должно быть того же типа, что и `x`, то получим ошибку "mismatched types" (несоответствие типов):

[example]
----
$ cargo run
   Compiling chapter10 v0.1.0 (file:///projects/chapter10)
error[E0308]: mismatched types
 --> src/main.rs:7:38
  |
7 |     let wont_work = Point { x: 5, y: 4.0 };
  |                                      ^^^ expected integer, found floating-point number

For more information about this error, try `rustc --explain E0308`.
error: could not compile `chapter10` due to previous error
----

Чтобы определить структуру `Point`, где `x` и `y` являются обобщенными, но могут иметь разные типы, можно использовать различные параметры обобщенного типа. Например, в листинге 10-8 мы изменили определение структуры `Point`, сделав ее обобщенной над типами `T` и `U`, где значение поля `x` относится к типу `T`, а значение поля `y` — к типу `U`.

--
.Листинг 10-8: Обобщенный объект Point<T, U> над двумя типов, так что x и y могут быть значениями разных типов

Файл: src/main.rs

[source,rust]
----
struct Point<T, U> {
    x: T,
    y: U,
}

fn main() {
    let both_integer = Point { x: 5, y: 10 };
    let both_float = Point { x: 1.0, y: 4.0 };
    let integer_and_float = Point { x: 5, y: 4.0 };
}
----
--

Теперь допустимы все показанные экземпляры `Point`! Вы можете использовать в определениях столько параметров обобщенного типа, сколько хотите, но заметим, что применение большого количества параметров в одном определении затрудняет чтение кода. Чаще всего такая ситуация является следствием неверного проектирования кода и указывает на необходимость его декомпозиции на более мелкие части.

==== В определениях перечислений

Как и в случае со структурами, можно определить перечисления для применения обобщенных типов данных в их вариантах. Давайте еще раз взглянем на перечисление `Option<T>` из стандартной библиотеки, которое мы использовали в <<_6_1_option,Главе 6>>:

[source,rust]
----
enum Option<T> {
    Some(T),
    None,
}
----

Теперь это определение должно быть вам понятно. Как видите, перечисление `Option<T>` является обобщенным над типом `T` и имеет два варианта: `Some`, который содержит одно значение типа `T`, и вариант `None`, который не содержит никакого значения. Используя перечисление `Option<T>`, мы можем выразить абстрактную концепцию необязательного значения, а поскольку `Option<T>` является обобщенным, то можем использовать эту абстракцию независимо от типа необязательного значения.

Перечисления также могут использовать несколько разных обобщенных типов. Одним из примеров является определение перечисления `Result`, которое мы использовали в <<_9_2_result,Главе 9>>:

[source,rust]
----
enum Result<T, E> {
    Ok(T),
    Err(E),
}
----

Перечисление `Result` является обобщенным над двумя типами, `T` и `E`, и имеет два варианта: `Ok`, который содержит значение типа `T`, и `Err`, который содержит значение типа `E`. С таким определением перечисление `Result` удобно применять в любой операции, которая может завершиться успешно и вернуть значение некоторого типа `T` или неудачно и вернуть ошибку некоторого типа `E`. Например, в операции открытия файла в листинге 9-3 параметр `T` будет типом `std::fs::File` в случае успешного открытия файла, а `E` — типом `std::io::Error` при возникновении проблем с открытием файла.

Если вы заметите, что определения структур или перечислений в вашем коде отличаются только типами содержащихся в них значений, то сможете убрать лишний код, заменяя повторы обобщенными типами.

==== В определениях методов

Мы можем использовать обобщенные типы в определениях методов структур и перечислений. В листинге 10-9 показана структура `Point<T>` с определением из листинга 10-6 и реализованным в ней методом `x`.

--
.Листинг 10-9: Реализация метода с именем x в структуре Point<T>, который будет возвращать ссылку на поле x типа T

Файл: src/main.rs

[source,rust]
----
struct Point<T> {
    x: T,
    y: T,
}

impl<T> Point<T> {
    fn x(&self) -> &T {
        &self.x
    }
}

fn main() {
    let p = Point { x: 5, y: 10 };

    println!("p.x = {}", p.x());
}
----
--

В приведенном коде определен метод с именем `x` для `Point<T>`, который возвращает ссылку на данные в поле `x`.

Обратите внимание, что нужно объявить параметр обобщенного типа `T` сразу после `impl`, тем самым мы информируем компилятор о применении обобщенного типа в реализации методов структуры `Point<T>`. Теперь Rust знает, что тип в угловых скобках в `Point` является обобщенным, а не конкретным типом. Можно было бы задать другое имя параметра обобщенного типа после `impl`, отличное от параметра, объявленного в определении структуры, но использование того же имени является общепринятым соглашением в Rust. Методы, написанные в блоке `impl` с параметром `T`, будут определены для любого экземпляра типа `Point<T>`, независимо от того, какой конкретный тип в конечном итоге будет использован вместо `T`, иными словами, являются _обобщенными методами_ обобщенной структуры `Point<T>`.

Помимо обобщенных методов обобщенной структуры можно определить методы для структур с заданным значением обобщенного типа, проще говоря, конкретным типом. Например, реализовать методы только для экземпляров `Point<f32>`, а не для экземпляров `Point<T>` с произвольным обобщенным типом. В листинге 10-10 мы используем конкретный тип `f32`, что означает, что после `impl` никакие типы не объявляются.

--
.Листинг 10-10: Блок impl, который применяется только к структуре с определенным конкретным типом для параметра обобщенного типа T

Файл: src/main.rs

[source,rust]
----
impl Point<f32> {
    fn distance_from_origin(&self) -> f32 {
        (self.x.powi(2) + self.y.powi(2)).sqrt()
    }
}
----
--

Этот код означает, что у конкретного типа `Point<f32>` будет конкретный метод `distance_from_origin`; у других экземпляров `Point<T>`, где `T` не является типом `f32`, этот метод определен не будет. Этот метод вычисляет расстояние от точки с координатами (0,0, 0,0) до точки `self` на евклидовой плоскости, и использует математические операции, доступные только для типов с плавающей запятой (поэтому обобщенная структура ограничена до типа `f32`).

Так как методы являются функциями, у которых могут быть параметры с обобщенными типами, вообще говоря, отличными от обобщенных типов в определении самой структуры, то это дает разработчику дополнительные возможности. В случае, когда параметры обобщенного типа в определении структуры не совпадают с типами, определенными для сигнатур методов этой же структуры, гибкость обобщенных типов проявляется в полной мере. Для примера рассмотрим код в листинге 10-11, в котором используются обобщенные типы `X1` и `Y1` для структуры `Point` и обобщенные типы `X2` и `Y2` для сигнатуры ее метода `mixup`. Метод создает новый экземпляр `Point` со значением `x` из текущего экземпляра `self` (типа `X1`) и значением `y` из переданного экземпляра `Point` (типа `Y2`).

--
.Листинг 10-11: Метод, который использует обобщенные типы, отличные от определения его структуры

Файл: src/main.rs

[source,rust]
----
struct Point<X1, Y1> {
    x: X1,
    y: Y1,
}

impl<X1, Y1> Point<X1, Y1> {
    fn mixup<X2, Y2>(self, other: Point<X2, Y2>) -> Point<X1, Y2> {
        Point {
            x: self.x,
            y: other.y,
        }
    }
}

fn main() {
    let p1 = Point { x: 5, y: 10.4 };
    let p2 = Point { x: "Hello", y: 'c' };

    let p3 = p1.mixup(p2);

    println!("p3.x = {}, p3.y = {}", p3.x, p3.y);
}
----
--

В функции `main` мы определили точку `p1`, у которой тип `i32` для `x` (со значением 5) и тип `f64` для `y` (со значением 10.4). Переменная `p2` представляет собой структуру `Point`, у которой тип `&str` для `x` (со значением "Hello") и `char` для `y` (со значением символа 'c'). Вызов метода `mixup` для `p1` с аргументом `p2` дает нам экземпляр `p3`, у которого будет тип `i32` для `x`, потому что `x` приходит из `p1` и тип `char` для `y`, потому что `y` приходит от `p2`. Макрос `println!` выведет `p3.x = 5, p3.y = c`.

Цель этого примера — продемонстрировать ситуацию, в которой одни параметры обобщенного типа объявляются с помощью `impl`, а другие — посредством определения метода. В приведенном примере параметры `X1` и `Y1` объявлены после `impl`, потому что так определена структура. Параметры `X2` и `Y2` объявляются после `fn mixup`, потому что они релевантны только в этом методе.

==== Производительность кода, использующего обобщенные типы

Может возникнуть вопрос, а есть ли накладные расходы во время выполнения (runtime cost) при использовании параметров обобщенного типа. Ответ: нет! Ваша программа с обобщенными типами будет работать точно также, как и с конкретными.

В Rust это достигается с помощью специальной техники, называемой "мономорфизацией кода", которая выполняется на этапе компиляции. _Мономорфизация_ (_monomorphization_) — это процесс превращения обобщенного кода в конкретный путем заполнения его на этапе компиляции используемыми в коде конкретными типами. В этом процессе компилятор выполняет действия, противоположные шагам, предпринятым для создания обобщенной функции в листинге 10-5: компилятор просматривает все места, где указан обобщенный код, и добавляет автоматически сгенерированный код с заменой обобщенного типа на тот конкретный тип, для которого вызывается этот обобщенный код; по завершении обобщенный код удаляется из текста программы.

Давайте посмотрим, как это работает, на примере перечисления `Option<T>` из стандартной библиотеки:

[source,rust]
----
let integer = Some(5);
let float = Some(5.0);
----

Когда Rust компилирует этот код, он выполняет мономорфизацию. В ходе этого процесса компилятор читает значения, указанные в экземплярах `Option<T>`, и идентифицирует два типа `Option<T>`: один — `i32`, а другой — `f64`. Так общее определение `Option<T>` расширяется до двух определений, специализированных для `i32` и `f64`, тем самым заменяя общее определение конкретными.

Мономорфизированная версия кода выглядит примерно так (компилятор использует имена, отличные от приведенных в примере для иллюстрации):

Файл: src/main.rs

[source,rust]
----
enum Option_i32 {
    Some(i32),
    None,
}

enum Option_f64 {
    Some(f64),
    None,
}

fn main() {
    let integer = Option_i32::Some(5);
    let float = Option_f64::Some(5.0);
}
----

Обобщенное перечисление `Option<T>` заменяется конкретными определениями, созданными компилятором. Поскольку Rust преобразует обобщенный код в код, в котором указан конкретный тип в каждом экземпляре, не возникает никаких накладных расходов от обобщенных типов во время выполнения. Когда код запускается, он работает так же, как если бы мы продублировали каждое определение вручную. Благодаря процессу мономорфизации обобщенные типы в Rust чрезвычайно эффективны во время выполнения.
