[#_1_1_installation]
=== 1.1. Установка

Первый шаг — установить Rust. Мы загрузим Rust через `rustup`, инструмент командной строки для управления версиями Rust и сопутствующими инструментами. Для загрузки потребуется подключение к Интернету.

[sidebar]
Если вы по какой-то причине предпочитаете не использовать `rustup`, для получения дополнительной информации см. страницу «Другие методы установки Rust» по адресу _https://forge.rust-lang.org/infra/other-installation-methods.html_.

Далее описаны шаги по установке последней стабильной версию компилятора Rust. Стабильная версия гарантирует, что все компилируемые примеры в книге будут продолжать компилироваться и с более новыми версиями компилятора Rust. Команда Rust постоянно работает над улучшением кода компилятора, поэтому в разных его версиях могут отличаться тексты сообщений об ошибках и предупреждениях. Это значит, что любая более новая стабильная версия Rust должна работать в соответствии с описанием в этой книге.

.Нотация командной строки
****
На протяжении всей книги мы будем показывать некоторые команды, которые пишем в консоли. Строки, которые вводятся в консоль, начинаются с `$`. Сам символ `$` вводить не нужно, это приглашение командной строки, отображаемое для указания начала каждой команды. Строки, не начинающиеся с `$`, обычно показывают результат предыдущей команды. Кроме того, в примерах, специфичных для PowerShell, приглашение имеет вид `>`, а не `$`.
****

==== Установка на ОС Linux и MacOS

Если вы используете ОС Linux или MacOS, откройте консоль и введите следующую команду:

 curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh

Команда загружает скрипт установки инструмента `rustup` и запускает его, который в свою очередь выполняет установку последней стабильной версию Rust; при этом может потребоваться ввод пароля. Если установка прошла успешно, появится следующая строка:

 Rust is installed now. Great!

Вам также понадобится _компоновщик_ (_linker_) — программа, которую Rust использует для объединения скомпилированных выходных данных в один файл. Скорее всего, он у вас уже есть. Если вы получаете ошибки компоновщика, то лучшим решением будет установить компилятор языка C, который обычно включает компоновщик. Компилятор языка C полезен еще и потому, что некоторые распространенные пакеты Rust написаны на языке C и для их использования в любом случае потребуется компиляция С-кода.

В MacOS вы можете установить компилятор языка C, выполнив команду:

 $ xcode-select --install

Пользователям ОС Linux достаточно установить компиляторы `gcc` или `clang` в соответствии с документацией их дистрибутива. Например, если вы используете Ubuntu, то для инсталляции gcc и clang можете просто установить пакет _build-essential_.

==== Установка rustup на ОС Windows

В ОС Windows перейдите на страницу _https://www.rust-lang.org/tools/install_ и следуйте инструкциям по установке Rust. В какой-то момент установки вы получите сообщение о том, что требуются инструменты сборки MSVC для Visual Studio 2013 или более поздней версии. Для этого необходимо установить Visual Studio 2022 со страницы _https://visualstudio.microsoft.com/downloads/_. Для продолжения установки потребуется выбрать необходимые рабочие пакеты (workloads-packages); укажите следующие:

* Desktop Development with C++
* The Windows 10 or 11 SDK
* Компонент английского языкового пакета вместе с любым другим языковым пакетом по вашему выбору.

В этой книги используются команды, которые работают как в _cmd.exe_, так и в PowerShell. При необходимости явного указания различий обязательно приводятся пояснения, что и как именно использовать.

==== Устранение неполадок

Чтобы проверить, правильно ли у вас установлен Rust, откройте консоль и введите следующую команду:

 $ rustc --version

Должен быть выведен текст с номером версии, хэшем и датой фиксации последней стабильной версии в следующем формате:

 rustc x.y.z (abcabcabc yyyy-mm-dd)

Если вы получили такой вывод, поздравляем с успешной установкой Rust! В противном случае, если у вас Windows, убедитесь, что Rust указан в системной переменной _%PATH%_.
Для этого в Windows cmd используйте команду:

 > echo %PATH%

В Windows PowerShell:

 > echo $env:Path

В ОС Linux и MacOS:

 echo $PATH

Если все верно, а Rust по-прежнему не работает, то хороший вариант решить проблему — обратиться за помощью в интернет-сообщества. В первую очередь это канал #beginners на официальном дискорде Rust, доступный по ссылке _https://discord.gg/rust-lang_. Там можно обсудить вашу проблему с опытными разработчиками Rust. Приведем ссылки и на другие замечательные ресурсы:

* Форум разработчиков Rust (_https://users.rust-lang.org/_),
* Страница Rust на Stack Overflow (_https://stackoverflow.com/questions/tagged/rust_).

==== Обновление и удаление

Обновиться до последней стабильной версии Rust очень просто. В консоли выполните команду:

 $ rustup update

Для удаления Rust и `rustup` выполните команду:

 $ rustup self uninstall

==== Локальная документация

Дистрибутив Rust также включает в себя локальную копию документации, поэтому после успешной установки ее можно читать в автономном режиме. Чтобы открыть локальную документацию в вашем браузере, просто выполните команду

 rustup doc

Если тип или функция предоставляется стандартной библиотекой, и вы не уверены, что они делают или как их использовать, обратитесь к документации соответствующего API за получением дополнительной информации!
