[#_1_2_hello_world]
=== 1.2. Hello, world!

Теперь, когда вы установили Rust, давайте напишем первую программу на Rust. Традиционно при изучении нового языка пишут небольшую программу, которая выводит на экран текст «Hello, world!», так что не будем нарушать традицию и сделаем здесь то же самое!

[sidebar]
В этой книге предполагается базовое знакомство с командной строкой. Rust не предъявляет особых требований к вашему текстовому редактору, инструментам или местонахождению вашего кода, поэтому если вы предпочитаете вместо командной строки использовать интегрированную среду разработки (IDE), можете это делать без проблем. Многие IDE теперь в той или иной степени поддерживают Rust; подробности см. в документации по IDE. Команда Rust обеспечила отличную поддержку IDE через `rust-analyzer`; см. Приложение D для более подробной информации.

==== Создание каталога проекта

Любой новый проект всегда будет начинаться с создания каталога для хранения кода Rust. Для Rust не имеет значения место расположения кода, но для удобства работы с учебными упражнениями и проектами предлагаем создать каталог _projects_ в вашем домашнем каталоге и хранить все учебные проекты там.

Чтобы создать каталог _projects_ и каталог для проекта «Hello, world!» в каталоге _projects_, откройте консоль и введите следующие команды.

Для ОС Linux, macOS и PowerShell в ОС Windows:

[example]
----
$ mkdir ~/projects
$ cd ~/projects
$ mkdir hello_world
$ cd hello_world`
----

Для Windows cmd:

[example]
----
> mkdir "%USERPROFILE%\projects"
> cd /d "%USERPROFILE%\projects"
> mkdir hello_world
> cd hello_world
----

==== Разработка и запуск программ Rust

Создайте новый исходный файл и назовите его _main.rs_. Файлы Rust всегда заканчиваются расширением _.rs_. Если в имени файла используется более одного слова, принято разделять их символом подчеркивания. Например, вместо _helloworld.rs_ должно быть _hello_world.rs_.

Теперь откройте в текстовом редакторе только что созданный файл _main.rs_ и введите код из листинга 1-1.

--
.Программа, которая печатает Hello, world!
[caption="Листинг {counter:my-example-number:1-1}: "]

Файл: main.rs

[source,rust]
----
fn main() {
    println!("Hello, world!");
}
----
--

Сохраните файл и вернитесь в каталог _~/projects/hello_world_. В Linux или macOS введите следующие команды для компиляции и запуска файла:

[example]
----
$ rustc main.rs
$ ./main
Hello, world!
----

В Windows введите команду _.\main.exe_ вместо _./main_:

[example]
----
> rustc main.rs
> .\main.exe
Hello, world!
----

Независимо от вашей операционной системы в консоли должен быть выведен текст «Hello, world!». Если этот текст не был выведен, вернитесь к секции «Устранение неполадок» раздела xref:_1_1_installation[«1.1 Установка»], чтобы узнать, как получить помощь.

Если вы видите текст «Hello, world!», поздравляем с первой написанной программой на Rust! Вы сделали первый шаг на пути разработчика Rust — добро пожаловать!

==== Анатомия программы на Rust

Давайте рассмотрим программу «Hello, world!» в деталях. Вот первая часть кода:

[source,rust]
----
fn main() {

}
----

Эти строки определяют функцию с именем `main`. Функция `main` особенная: это код, с которого всегда начинает запускаться каждая исполняемая программа Rust. Определение функции начинается с ее объявления — `main` объявлена как функция, которая не имеет параметров и ничего не возвращает. Параметры функции указываются внутри круглых скобок `()`.

Тело функции `main` заключено в `{}`. В Rust тело любой функции должно размещаться внутри фигурных скобок. Хороший стиль — разместить открывающую фигурную скобку на той же строке, что и объявление функции, добавив между ними один пробел.

[sidebar]
Если вы хотите придерживаться стандартного стиля в проектах Rust, то можете использовать утилиту `rustfmt` для автоматического форматирования кода в каноническом стиле Rust (подробнее о rustfmt говорится в Приложении D). Команда Rust включила эту утилиту в стандартный дистрибутив Rust, так что она уже должна быть установлена на вашем компьютере!

Тело функции `main` содержит следующий код:

[source,rust]
----
    println!("Hello, world!");
----

Эта строка выполняет всю работу в нашей маленькой программе: она выводит текст на экран. Здесь следует обратить внимание на четыре важные детали.

Во-первых, стиль Rust предполагает отступ в четыре пробела, а не табуляцию.

Во-вторых, `println!` является макросом, а не функцией. Если бы вместо макроса использовалась функция, то ее вызов выглядел бы как `println` — без `!`. Мы обсудим макросы Rust более подробно в Главе 19. Сейчас достаточно знать, что `!` является атрибутом макроса и что макросы не всегда следуют тем же правилам, что и функции.

В-третьих, строковый литерал `"Hello, world!"`. Этот литерал передается в качестве аргумента макросу `println!` для вывода текста литерала в консоль.

В-четвертых, текстовая строка заканчивается точкой с запятой, которая обозначает конец текущего выражения. Большинство текстовых строк в коде Rust заканчиваются точкой с запятой.

==== Компиляция и запуск — это отдельные шаги

Итак, нам удалось запустить нашу первую программу, поэтому давайте рассмотрим каждый шаг в этом процессе.

Перед запуском программы ее нужно скомпилировать с помощью компилятора Rust, используя команду rustc, на вход которой нужно передать имя вашего исходного файла, например:

 $ rustc main.rs

Если у вас есть опыт работы с языками C или C++, вы заметите, что это очень похоже на то, как происходит компиляции в [.st]#gcc# или [.st]#clang#. После успешной компиляции Rust генерирует двоичный исполняемый (далее просто исполняемый) файл.

В ОС Linux и macOS введите команду ls в консоли и увидите два файла — файл с исходным кодом программы (_main.rs_) и исполняемый файл (_main_):

[example]
----
$ ls
main  main.rs
----

Команду `ls` можно использовать и в Windows PowerShell, а в cmd нужно ввести команду `dir /B` (опция `/B` позволяет показывать только имена файлов):

[example]
----
> dir /B
main.exe
main.pdb
main.rs
----

В ОС Windows видим три файла — файл исходного кода с расширением _.rs_, исполняемый файл _main.exe_ и файл с отладочной информацией с расширением _.pdb_. Последний файл создается только в ОС Windows, в других системах его нет.

Отсюда вы запускаете исполняемый файл, например:

в ОС Linux или MacOS

 $ ./main

в ОС Windows

 > .\main.exe

Если _main.rs_ — это наша программа «Hello, world!», то при запуске исполняемого файла она выведет в консоль текст «Hello, world!».

В таких динамических языках, как Ruby, Python или JavaScript, для запуска программы не требуется ее предварительная компиляция как отдельный шаг процесса. В отличие от них Rust является языком с _предварительной компиляцией_ (_ahead-of-time compiled_). Что это дает? После компиляции программы, полученный исполняемый файл можно запустить на любом другом компьютере (_Примечание переводчика: разумеется с той же самой операционной системой_) без установленного Rust. Проделать такое с файлами .rb, .py или .js без установленного Ruby, Python или JavaScript на другом компьютере, увы, не получится. С другой стороны, в этих языках нужна только одна команда для компиляции и запуска вашей программы (_Примечание переводчика: и не требуется перекомпилировать исходный код при запуске в другой операционной системе_). В языковом дизайне все является компромиссом.

Компиляция с помощью `rustc` подходит только для простых программ, по мере роста вашего проекта вам захочется управлять всеми параметрами сборки и публикацией кода для совместного использования. Далее мы познакомимся с пакетом Cargo, с помощью которого вы сможете создавать профессиональные программы на Rust.
