[#_chapter_2]
== Глава 2. Программирование игры в угадайку

Давайте начнем наше погружение в Rust, вместе поработав над первым практическим проектом! В этой главе вы познакомитесь с несколькими общими концепциями Rust на примере их использования в реальной программе. Вы узнаете о `let`, `match`, методах, ассоциированных функциях, использовании внешних крейтов и многом другом! В следующих главах мы рассмотрим все это более подробно. А в этой главе попрактикуемся в основах.

Мы реализуем классическую задачу для начинающих программистов: игру в угадайку. Программа генерирует случайное целое число от 1 до 100. Затем предлагает игроку ввести свое число-догадку (guess number). После ввода числа программа сообщит, больше оно или меньше случайного числа. Если числа совпадают, игра напечатает поздравительное сообщение и завершится.

=== Настройка нового проекта

Давайте перейдем в каталог _projects_, который создали в Главе 1, и создадим с помощью Cargo новый проект `guessing_game`:

[example]
----
$ cargo new guessing_game
$ cd guessing_game
----

Первая команда, `cargo new`, принимает в качестве первого аргумента название проекта (`guessing_game`) и создает новый проект. Вторая команда переходит в каталог нового проекта.

Посмотрим на сгенерированный файл _Cargo.toml_:

[example]
----
[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
----

Как известно из Главы 1, команда `cargo new` автоматически генерирует программу «Hello, world!». Проверим файл _src/main.rs_ и убедимся, что так и есть:

Файл: src/main.rs

[source,rust]
----
fn main() {
    println!("Hello, world!");
}
----

Теперь давайте скомпилируем и запустим эту программу с помощью команды `cargo run`:

[example]
----
$ cargo run
   Compiling guessing_game v0.1.0 (file:///projects/guessing_game)
    Finished dev [unoptimized + debuginfo] target(s) in 1.50s
     Running `target/debug/guessing_game`
Hello, world!
----

Команда `cargo run` удобна, когда нужно быстро запустить исполняемый файл проекта; мы будем пользоваться этой командой постоянно, переходя от одной итерации изменения проекта в другой.

Снова откроем файл _src/main.rs_. Будем писать весь код в этом файле.

include::rb-2-1-processing-guess.adoc[]

include::rb-2-2-generating-secret-number.adoc[]

include::rb-2-3-comparing.adoc[]

include::rb-2-4-looping.adoc[]

include::rb-2-5-summary.adoc[]
