[#_3_4_comments]
=== 3.4. Комментарии

Многие программисты стремятся сделать свой код доступным для понимания, но иногда требуются дополнительные пояснения. В этих случаях разработчики оставляют _комментарии_ в своем исходном коде, которые компилятор проигнорирует, но для читателей исходного кода, они могут оказаться полезными.

Вот простой комментарий:

[source,rust]
----
// hello, world
----

В Rust идиоматический стиль комментариев начинается с двух косых черт и продолжается до конца строки. Для комментариев, выходящих за пределы одной строки, нужно включить `//` в каждую строку, например:

[source,rust]
----
// Здесь мы собираемся сделать что-то сложное, так что объяснение
// этого может потребовать комментария из нескольких строк! Надеемся,
// этот комментарий объяснит, что происходит далее.
----

Комментарии также можно размещать в конце строк, содержащих код:

Файл: src/main.rs

[source,rust]
----
fn main() {
    let lucky_number = 7; // Мне сегодня везет
}
----

Но чаще всего комментарии размещаются в отдельных строках над кодом, к которому они относятся:

Файл: src/main.rs

[source,rust]
----
fn main() {
    // Мне сегодня везет
    let lucky_number = 7;
}
----

Если требуется закомментировать большие участки кода, то в Rust можно использовать комментарии вида `+/* ... */+` как в языках С или C++. В точке кода, с которой начинается такой комментарий, пишем тэг `pass:[/*]`; в точке кода, где он заканчивается, пишем тэг `pass:[*/]`. При компиляции Rust игнорирует весь текст, который оказался между этими двумя тэгами.

Наконец, в Rust также есть комментарии, начинающиеся на три косые черты, `///`. Читателям, знакомым с языком Python, этот вид комментариев хорошо известен. Это комментарии, текст которых попадает в вывод команды `cargo open --doc`, или, другими словами, они выполняют дополнительную функцию документирования кода. Об этих комментариях мы поговорим подробнее в разделе «Публикация крейта на crates.io» Главы 14.
