[#_chapter_3]
== Глава 3. Общие концепции программирования

В этой главе рассматриваются концепции, встречающиеся почти в каждом языке программирования, и как они работают в Rust. В своей основе большинство языков программирования имеют много общего. Ни одна из концепций, представленных в этой главе, не является уникальной для Rust, но мы обсудим их в контексте Rust и объясним соглашения, связанные с использованием этих концепций.

В частности, мы узнаем о переменных, основных типах, функциях, комментариях и потоке управления. Эти конструкции будут в каждой программе на Rust, и изучение их на раннем этапе даст хорошую базу начинающему разработчику Rust.

[sidebar]
.Ключевые слова
Как и в других языках, в Rust есть набор _ключевых слов_, зарезервированных для использования только самим языком. Имейте в виду, что не можете использовать эти слова в качестве имен переменных или функций. Большинство ключевых слов имеют особое значение, и будут использоваться для выполнения различных задач в программах на Rust; у некоторых из этих слов на данный момент нет реализованной функциональности, но они зарезервированы для реализации этой функциональности в будущем. Вы можете найти список ключевых слов в Приложении A.

include::rb-3-1-variables.adoc[]

include::rb-3-2-data-types.adoc[]

include::rb-3-3-functions.adoc[]

include::rb-3-4-comments.adoc[]

include::rb-3-5-control-flow.adoc[]

include::rb-3-6-summary.adoc[]
