[#_5_3_method_syntax]
=== 5.3. Синтаксис методов

_Методы_ (methods) похожи на функции: мы объявляем их с помощью ключевого слова `fn` и имени, они могут иметь параметры и возвращаемое значение, и содержат код, который выполняется при вызове метода. В отличие от функций, методы определяются в контексте структуры (или перечисления, или трейт-объекта, которые мы рассмотрим в xref:_chapter_6[Главе 6] и Главе 17 соответственно), и их первым параметром всегда является `self`, который для каждого метода представляет экземпляр структуры, вызывающей этот метод.

==== Определение методов

Давайте изменим функцию `area` с параметром `Rectangle`, и вместо нее создадим одноименный метод, определенный в структуре `Rectangle`, как показано в листинге 5-13.

--
.Листинг 5-13: Определение метода area в структуре Rectangle

Файл: src/main.rs

[source,rust]
----
#[derive(Debug)]
struct Rectangle {
    width: u32,
    height: u32,
}

impl Rectangle {
    fn area(&self) -> u32 {
        self.width * self.height
    }
}

fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    println!(
        "The area of the rectangle is {} square pixels.",
        rect1.area()
    );
}
----
--

Чтобы определить функцию в контексте `Rectangle`, мы начинаем с блока `impl Rectangle`; в этом блоке всё будет связано с нашим типом `Rectangle`. Затем размещаем функцию `area` внутрь фигурных скобок `impl` и меняем первый (и в данном случае единственный) параметр на `self` в ее сигнатуре и теле. В функции `main` мы вызывали `area` и передавали `rect1` в качестве аргумента, теперь вместо этого можем применить в нашем экземпляре `Rectangle` синтаксис метода для вызова метода `area`. Синтаксис метода начинается сразу после имени экземпляра: мы добавляем точку, за которой следует имя вызываемого метода, круглые скобки и необходимые аргументы.

В сигнатуре `area` вместо `rectangle: &Rectangle` используется `&self`. Ссылка `&self` на самом деле является сокращением от `self: &Self`. Внутри блока `impl` тип `Self` является псевдонимом типа, наименование которого указано после `impl`. У методов первым параметром всегда должен быть `self` типа `Self` (`self: Self`), поэтому Rust позволяет указывать его в сокращенной форме — просто как `self`. Обратите внимание, что в случае заимствования в методе экземпляра `Self` нужно использовать символ `&` в сокращенной форме `self`, точно так же, как в `rectangle: &Rectangle`. Методы могут забирать `self` во владение, заимствовать его без изменения (как в нашем случае), или с изменением; `self` в этом плане ничем не отличается от любого другого параметра.

Заимствование без изменения (`&self`) выбрано по той же причине, по какой используется `&Rectangle` в функции `area`: нам достаточно только читать данные из структуры, изменять ее не нужно. Если метод должен изменять вызывающий его экземпляр, то в качестве первого параметра такого метода следует использовать `&mut self`. Вариант, когда метод становится владельцем экземпляра, используя `self` как единственный параметр, встречается редко; такой метод обычно применяется при преобразовании `self` в значение другого типа, при этом вызывающей стороне запрещается использовать исходный экземпляр после преобразования.

Основная причина применения методов вместо функций, помимо удобного синтаксиса метода и отсутствия необходимости повторять наименование типа в сигнатуре каждого метода, заключается в организации типа. Мы поместили все, что можем делать с экземпляром типа, в один блок `impl` вместо того, чтобы вынуждать будущих пользователей нашего кода искать информацию о возможностях `Rectangle` во всей предоставляемой нами библиотеке.

Обратите внимание, что можно дать методу то же имя, что и одному из полей структуры. Например, определим метод для `Rectangle` с именем `width`:

Файл: src/main.rs

[source,rust]
----
impl Rectangle {
    fn width(&self) -> bool {
        self.width > 0
    }
}

fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    if rect1.width() {
        println!("The rectangle has a nonzero width; it is {}", rect1.width);
    }
}
----

Метод `width` возвращает значение `true`, если значение в поле `width` экземпляра больше 0, и значение `false`, если значение равно 0: ограничений по использованию поля в одноименном методе нет. Когда Rust встречает в функции `main` выражение `rect1.width` со скобками, то знает, что имеется в виду метод `width`. Когда круглые скобки не используются, Rust понимает, что речь идет о поле `width`.

Часто, но не всегда, метод называется тем же именем, что и поле, когда требуется, чтобы он возвращал только значение этого поля и ничего больше не делал. Такие методы называются _геттерами_, и в некоторых объектно-ориентированных языках они реализуются для полей структуры автоматически; в Rust такого нет. Геттеры полезны в ситуации, когда нужно читать значение закрытого поля: для этого создается геттер, который становится частью предоставляемого нами открытого API. В xref:_chapter_7[Главе 7] мы подробно обсудим доступ к элементам структур данных и модулей и как с ним работать.

.А где оператор `—>`?
****
В языках C и C++ для вызова методов используются два разных оператора: оператор "точка (`.`) для прямого вызова метода из объекта и оператор "стрелка" (`—>`), когда метод вызывается из указателя на объект, для чего этот указатель сначала разыменовывается. Другими словами, если `object` является указателем, синтаксис функции `object—>something()` аналогичен синтаксису `(*object).something()`.

В Rust нет эквивалента оператору `—>`; вместо этого в Rust есть поведение, которое называется _автоматическим взятием ссылки и разыменованием_ (_automatic referencing and dereferencing_). Вызов методов — одно из немногих мест в Rust, где используется это поведение.

Выглядит это так: когда вызывается метод `object.something()`, Rust автоматически добавляет `&`, `&mut` или `+*+` к `object` для приведения его в соответствие сигнатуре метода. Например, вызов метода `p1.distance(&p2);` является эквивалентным вызову `(&p1).distance(&p2);`. Первый выглядит намного чище.

Такое поведение с автоматическим взятием ссылок работает потому, что у методов есть очевидный получатель — экземпляр `self` (типа `Self`). Зная получателя и имя метода, Rust может определить, является ли метод читающим (`&self`), изменяющим (`&mut self`) или "потребляющим" (`self`). Неявное заимствование вызывающих методы экземпляров является важной частью эргономичности системы владения Rust на практике.
****

==== Методы с несколькими параметрами

Давайте попрактикуемся в использовании методов, и реализуем второй метод в структуре `Rectangle`. На этот раз мы хотим, чтобы экземпляр `Rectangle` брал другой экземпляр `Rectangle` и возвращал `true`, если второй `Rectangle` может полностью поместиться внутри `self` (= первом `Rectangle`); в противном случае он должен вернуть `false`. Назовем этот метод `can_hold`. Представим, что `can_hold` реализован, тогда у нас должна быть возможность написать программу, показанную в листинге 5-14 (_Примечание переводчика: здесь авторы здесь применяют методику test-driven_development, то есть "разработку от тестов"_).

--
.Листинг 5-14: Использование еще не написанного метода can_hold

Файл: src/main.rs

[source,rust]
----
fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };
    let rect2 = Rectangle {
        width: 10,
        height: 40,
    };
    let rect3 = Rectangle {
        width: 60,
        height: 45,
    };

    println!("Can rect1 hold rect2? {}", rect1.can_hold(&rect2));
    println!("Can rect1 hold rect3? {}", rect1.can_hold(&rect3));
}
----
--

Так как оба размера `rect2` меньше соответствующих размеров `rect1`, а `rect3` шире, чем `rect1`, то ожидаемый результат должен выглядеть следующим образом:

[example]
----
Can rect1 hold rect2? true
Can rect1 hold rect3? false
----

Мы знаем, что хотим определить метод, поэтому он будет внутри блока `impl Rectangle`. Имя метода будет `can_hold`, и в качестве параметра он будет принимать неизменяемое заимствование другого `Rectangle`. Мы можем сказать, какого типа будет этот параметр, взглянув на код, вызывающий метод: `rect1.can_hold(&rect2)` передает `&rect2`, то есть неизменяемую ссылку на `rect2`, экземпляр `Rectangle`. Это разумно, потому что `rect2` достаточно только читать (для его модификации пришлось бы использовать изменяемое заимствование), и мы хотим, чтобы функция `main` сохранила владение `rect2` для его использования после вызова метода `can_hold`. Возвращаемое значение `can_hold` будет иметь логическим тип, а реализация проверит, больше ли ширина и высота `self`, чем ширина и высота другого `Rectangle` соответственно. Давайте добавим новый метод `can_hold` в блок `impl` из листинга 5-13, как показано в листинге 5-15.

--
.Листинг 5-15: Реализация метода can_hold для Rectangle и другим экземпляром Rectangle в качестве параметра

Файл: src/main.rs

[source,rust]
----
impl Rectangle {
    fn area(&self) -> u32 {
        self.width * self.height
    }

    fn can_hold(&self, other: &Rectangle) -> bool {
        self.width > other.width && self.height > other.height
    }
}
----
--

После запуска этого кода с функцией `main` из листинга 5-14, получим ожидаемый результат. Методы могут принимать несколько параметров, которые мы добавляем в сигнатуру после параметра `self`, и эти параметры работают так же, как параметры в функциях.

==== Ассоциированные функции

Все функции, определенные в блоке `impl`, называются _ассоциированными функциями_, поскольку они связаны с типом, наименование которого указано сразу после ключевого слова `impl`. Можно определить ассоциированные функции, у которых `self` не является первым параметром (и, следовательно, такие функции не являются методами), потому что им не нужен экземпляр типа для своей работы. Мы уже использовали одну такую функцию, определенную для типа `String` — `String::from`.

Ассоциированные функции, не являющиеся методами, часто применяются в качестве конструкторов, возвращающих новый экземпляр структуры.

[sidebar]
Конструкторам обычно дают наименование `new`, при этом важно отметить, что `new` не является специальным именем и не встроено в язык.

Например, можно определить ассоциированную функцию с именем `square` и одним параметром размера, используемым как ширина и высота, вместо указания в конструкторе `Rectangle` одного и то же значение дважды, что упрощает создание квадратного `Rectangle`:

Файл: src/main.rs

[source,rust]
----
impl Rectangle {
    fn square(size: u32) -> Self {
        Self {
            width: size,
            height: size,
        }
    }
}
----

Ключевое слово `Self` в возвращаемом типе и в теле функции является [.underline]#псевдонимом для типа, наименование которого указано после `impl`#, в нашем случае `Rectangle`.

Для вызова ассоциированной функции используется синтаксис `::` с указанием имени структуры; например, `let sq = Rectangle::square(3);`. Пространство имен (namespace) для ассоциированной функции задается блоком `struct`; синтаксис `::` применяется как для ассоциированных функций, так и для пространств имен, созданных модулями. Мы обсудим и этот синтаксис и модули более детально в xref:_chapter_7[Главе 7].

==== Несколько блоков impl

Каждая структура может иметь несколько блоков `impl`. Например, листинг 5-15 эквивалентен коду, показанному в листинге 5-16, но теперь каждый метод находится в своем собственном блоке `impl`.

--
.Листинг 5-16: Переписывание листинга 5-15 с использованием нескольких блоков impl

Файл: src/main.rs

[source,rust]
----
impl Rectangle {
    fn area(&self) -> u32 {
        self.width * self.height
    }
}

impl Rectangle {
    fn can_hold(&self, other: &Rectangle) -> bool {
        self.width > other.width && self.height > other.height
    }
}
----
--

Здесь нет причин разделять методы на несколько блоков `impl`, но это допустимый синтаксис. В Главе 10 при обсуждении обобщенных типов и трейтов мы покажем случай, в котором несколько блоков реализации могут оказаться полезными.
