[#_chapter_5]
== Глава 5. Использование структур для группировки связанных данных

_Структура_ (_structures_ = _struct_) — это настраиваемый тип данных, который позволяет упаковывать вместе и именовать несколько связанных значений, составляющих значимую группу. Если вы знакомы с объектно-ориентированными языками, то можете представлять _структуру_ как атрибуты данных объекта. В этой главе мы, опираясь на текущие знания, сравним кортежи со структурами, и покажем, в каких случаях структуры являются лучшим способом группировки данных.

Мы объясним, как определять и создавать экземпляры структур; обсудим ассоциированные функции, особенно их подвиды, которые называются _методами_ и используются для спецификации поведения, связанного с типом структуры. Структуры и перечисления (обсуждаемые в xref:_chapter_6[Главе 6]) являются "строительными" блоками для создания новых типов в предметной области вашей программы, чтобы в полной мере пользоваться преимуществами проверки типов во время компиляции Rust.

include::rb-5-1-defining structs.adoc[]

include::rb-5-2-using-structs.adoc[]

include::rb-5-3-method-syntax.adoc[]

include::rb-5-4-summary.adoc[]
