[#_chapter_7]
== Глава 7. Управление большими проектами с помощью пакетов, крейтов и модулей

При разработке больших программ становится важным вопрос организации (и реорганизации) кода. Его решение основывается на группировке связанных функций и разделении кода на отдельные компоненты, при этом нужно уметь указывать место, где находится область кода, реализующая конкретную функцию.

Программы, которые мы писали до сих пор, размещались в одном модуле в одном файле. По мере роста проекта возникает необходимость организовывать код, разбивая его на несколько модулей, а затем — и отдельные модули на несколько файлов. Пакет (package) может содержать несколько бинарных крейтов и, возможно, один библиотечный крейт. Можно переносить части пакета в отдельные крейты, которые становятся внешними зависимостями и должны включаться в файл _Cargo.toml_. В этой главе рассматриваются технические методы организации кода. Для очень больших проектов, состоящих из набора взаимосвязанных пакетов, Cargo предоставляет _рабочие пространства_ (_workspaces_), которые мы рассмотрим в разделе «Рабочие пространства Cargo» Главы 14.

Также обсудим детали инкапсуляции реализации, которые позволяют повторно использовать код на более высоком уровне: как только вы реализовали операцию, другой код может вызывать ваш код через свой открытый интерфейс, не зная, как работает реализация. Решение о том, какие части являются открытыми для использования другим кодом, а какие — закрытыми, остается за вами как разработчиком; заметим, что это еще один способ уменьшить количество деталей, которые нужно держать в голове при разработке большого проекта.

Связанное с этим понятие — область действия: вложенный контекст кода имеет множество имен, которые привязываются к конкретной области действия. Знание того, к какому элементу относится конкретное имя в конкретном месте — переменной, функции, структуре, перечислению, модулю, константе или другому элементу — и что этот элемент означает, является важным при работе (чтение, разработка, компиляция) с кодом. Вы можете создавать новые области действия и изменять имена, которые входят в область действия или выходят за ее пределы. Учтите — не может быть двух элементов с одинаковыми именами в одной области действия, что позволяет избежать конфликта имен.

В Rust есть ряд функций, которые позволяют управлять организацией вашего кода, в том числе, конфиденциальностью (какие элементы являются открытыми, какие — закрытыми), и пространствами имен (какие имена находятся в каждой области действия). Эти функции, иногда вместе называемые _модульной системой_, включают в себя:

* *Пакеты*: функциональность Cargo, которая позволяет создавать, тестировать и совместно использовать несколько крейтов.
* *Крейты*: дерево модулей, которое создает библиотеку или исполняемый файл.
* *Модули* и *use*: позволяют контролировать организацию, область действия и конфиденциальность путей.
* *Пути*: способ именования элемента, такого как структура, функция или модуль.

В этой главе мы рассмотрим все эти функции, обсудим, как они взаимодействуют, и объясним, как их использовать для управления областью действия. К концу вы должны хорошо понимать модульную систему и уметь профессионально работать с областями действия!

include::rb-7-1-packages-crates.adoc[]

include::rb-7-2-modules-scopes.adoc[]

include::rb-7-3-paths.adoc[]

include::rb-7-4-keyword-use.adoc[]

include::rb-7-5-modules-in-other-files.adoc[]

include::rb-7-6-summary.adoc[]
