[#_chapter_8]
== Глава 8. Коллекции из стандартной библиотеки

Стандартная библиотека Rust включает ряд очень полезных структур данных, называемых _коллекциями_. Большинство других типов данных представляют одно конкретное значение, но коллекции могут содержать несколько значений. В отличие от встроенных типов массивов и кортежей, данные, на которые указывают коллекции, хранятся в куче, что означает, что объем данных не нужно знать во время компиляции, и он может увеличиваться или уменьшаться по мере выполнения программы. Коллекции различаются по своим возможностям и накладным расходам, и выбор подходящего типа для вашей текущей ситуации — это навык, который вы разовьете со временем. В этой главе мы обсудим три коллекции, которые очень часто используются в программах на Rust:

* _Вектор_ (_vector_) позволяет хранить переменное количество значений последовательно друг за другом.
* _Строка_ (_string_) представляет собой набор символов. Ранее мы упоминали тип `String`, но в этой главе поговорим о нем более подробно.
* _Хэшированные отображения_ (_hash map_) позволяет связать значение с определенным ключом. Это конкретная реализация более общей структуры данных, называемой _отображением_ (_map_).

Чтобы узнать о других типах коллекций, предоставляемых стандартной библиотекой, см. документацию по адресу _https://doc.rust-lang.org/std/collections/index.html_.

Мы обсудим, как создавать и изменять векторы, строки и хэшированные отображения, а также их особенности.

include::rb-8-1-vectors.adoc[]

include::rb-8-2-strings.adoc[]

include::rb-8-3-hash-maps.adoc[]

include::rb-8-4-summary.adoc[]
