=== Резюме

Векторы, строки и хэшированные отображения обеспечивают большое количество функциональности, необходимой в программах, когда вам нужно хранить, получать доступ и изменять данные. Чтобы закрепить понимание материала этой главы, приведем несколько упражнений, которые настоятельно рекомендуем решить самостоятельно, прежде чем переходить к следующим главам:

* Дан список целых чисел, используйте вектор и верните медиану (значение в средней позиции после сортировки значений) и моду (значение, которое встречается чаще всего; здесь будет полезно хэшированное отображение) списка.

* Преобразование строк в поросячью латиницу (pig latin). Правила преобразования: первая согласная каждого слова перемещается в конец слова и добавляется «ау», так что «first» превращается в «irst-fay». К словам, начинающимся с гласной, просто добавляется «hay» (например, «apple» становится «apple-hay»). Помните о деталях кодировки UTF-8!

* Используя хэшированное отображение и векторы, создайте текстовый интерфейс, позволяющий пользователю добавлять имена сотрудников в отдел компании. Например, «Add Sally to Engineering» или «Add Amir to Sales». Затем реализуйте функции, которые позволяют пользователю получить список всех сотрудников отдела или всех сотрудников компании по отделам, отсортированный по алфавиту.

В документации стандартной библиотеки, описывающей функции векторов, строк и хэшированных отображений, вы можете найти все необходимое для решения этих упражнений!

Мы переходим к более сложным программам, в которых операции могут завершаться сбоем, поэтому самое время обсудить обработку ошибок. Это и станет следующей главы!
