[#_chapter_9]
== Глава 9. Обработка ошибок

Ошибки — это неотъемлемая часть программного обеспечения, поэтому в Rust есть ряд функций для обработки ошибочных ситуаций. Во многих случаях Rust требует, чтобы вы согласились с возможностью ошибки и предприняли некоторые действия по ее обработке, прежде чем ваш код будет скомпилирован. Это требование повышает надежность программ, гарантируя, что ошибки будут обнаружены и надлежащим образом обработаны до того, как код будет развернут в рабочей среде (production)!

Rust группирует ошибки в две основные категории: _устранимые_ (_recoverable_) и _неустранимые_ (_unrecoverable_). В случае устранимой ошибки, такой как «файл не найден», достаточно просто сообщить о проблеме пользователю и повторить операцию. Неустранимые ошибки всегда являются симптомами багов (некорректной реализации кода), например, попытка доступа к элементу за пределами границ массива, и в этом случае лучше немедленно остановить выполнение программы.

Большинство языков не различают эти ошибки и обрабатывают их одинаково, используя такие механизмы как исключения. В Rust нет исключений. Вместо этого есть тип `Result<T, E>` для работы с устранимыми ошибками и макрос `panic!` для аварийного завершения выполнения, когда программа сталкивается с неустранимой ошибкой. В этой главе мы сначала рассмотрим вызов `panic!`, затем расскажем о возврате значений `Result<T, E>`. Кроме того, обсудим, в каких ситуациях лучше попытаться восстановиться после ошибки, а в каких — немедленно завершить выполнение.

include::rb-9-1-panic.adoc[]

include::rb-9-2-result.adoc[]

include::rb-9-3-panic-or-not-to-panic.adoc[]

include::rb-9-4-summary.adoc[]
