=== Резюме

Функции обработки ошибок Rust разработаны, чтобы помочь вам писать более надежный код. Макрос `panic!` сигнализирует о том, что ваша программа находится в состоянии, которое она не может (или не должна) обработать, и позволяет остановить выполнение вместо того, чтобы пытаться продолжить работу с недопустимыми или неправильными значениями. Перечисление `Result` использует систему типов Rust для указания на то, что операции могут завершиться неудачей, но таким образом, что ваш код в состоянии восстановиться и продолжить выполнение. Result можно применять, чтобы сообщить программе, вызывающей ваш код, что она также должна обрабатывать успешный или неуспешный варианты результирующего значения. Использование `panic!` и `Result` в соответствующих ситуациях сделают ваш код более надежным в условиях реальной эксплуатации с ее неизбежными проблемами.

Теперь, когда вы увидели полезные способы применения в стандартной библиотеке обобщенных типов (дженериков) с перечислениями `Option` и `Result`, поговорим о том, как работают дженерики и как их использовать в своем коде.
