== Предисловие

Не сразу, но с течением времени, становится все более очевидным, что язык программирования Rust направлен на расширение ваших возможностей. Независимо от того, какой код вы сейчас пишете, Rust позволяет вам идти дальше и уверенно программировать в более широком спектре областей, чем вы делали до этого.

Возьмем, к примеру, работу «системного уровня», связанную с низкоуровневыми деталями управления памятью, представлением данных и параллелизмом. Традиционно эта область программирования считается загадочной, доступной лишь немногим избранным, потратившим годы на обучение, чтобы избежать печально известных ловушек. И даже те, кто постоянно сталкивается с такими задачами на практике, делают это с осторожностью, чтобы их код не был открыт для эксплойтов, сбоев или повреждений.

Rust разрушает эти барьеры, устраняя старые ловушки и предоставляя дружественный, отточенный набор инструментов, которые помогут вам на этом пути. Программисты, которым нужно «погрузиться» в более низкоуровневый контроль, могут сделать это с помощью Rust, не принимая на себя обычный риск сбоев или дыр в безопасности, и избегая необходимости изучать тонкости непостоянного набора инструментов. Более того, язык предназначен для того, чтобы естественным образом направлять вас к надежному коду, эффективному с точки зрения скорости и использования памяти.

Программисты, которые уже работают с низкоуровневым кодом, могут использовать Rust для повышения своих амбиций. Например, внедрение параллелизма в Rust — операция с относительно низким риском: компилятор сам поймает классические ошибки. И вы можете заняться более серьезной оптимизацией своего кода с уверенностью, что она случайно не приведет к сбоям или уязвимостям.

Но Rust не ограничивается низкоуровневым системным программированием. Он достаточно выразительный и эргономичный, чтобы сделать приложения командной строки, веб-серверы и многие другие виды кода весьма приятными для написания — простые примеры того и другого вы найдете далее в книге. Работа с Rust позволяет вам развивать навыки, переносимые из одной области в другую; вы можете изучить Rust, написав веб-приложение, а затем применить те же навыки для своего Raspberry Pi.

Эта книга полностью раскрывает потенциал Rust для расширения возможностей пользователей. Это дружественный и доступный текст, призванный помочь вам повысить уровень не только ваших знаний о Rust, но и ваших возможностей и уверенности в себе как программиста в целом. Так что приготовьтесь учиться — и добро пожаловать в сообщество Rust!

— _Nicholas Matsakis, Aaron Turon_
