== Введение

Добро пожаловать в *Язык программирования Rust*!

Rust помогает писать более быстрое и надежное программное обеспечение. Высокоуровневая эргономика и низкоуровневый контроль часто противоречат друг другу в дизайне языка программирования; Rust бросает вызов этому конфликту. Сочетая мощные технические возможности и отличный опыт разработчиков, Rust предоставляет возможность контролировать низкоуровневые детали (например, использование памяти) без дополнительных накладных расходов, традиционно связанных с таким контролем.

=== Для кого Rust

Rust идеален для многих людей по разным причинам. Рассмотрим несколько важных групп.

Команды разработчиков::

Rust оказался продуктивным инструментом для совместной работы больших команд разработчиков с разным уровнем знаний системного программирования. Низкоуровневый код подвержен множеству незаметных ошибок, которые в большинстве других языков можно обнаружить только путем всестороннего тестирования и тщательного анализа кода опытными разработчиками. В Rust компилятор играет роль "привратника" (gatekeeper), отказываясь компилировать код с этими неуловимыми ошибками, включая ошибки параллелизма. Работая вместе с компилятором, команда может сосредоточиться на логике программы, а не на поиске ошибок.
+
Rust также привносит современные инструменты разработки в мир системного программирования:

* Cargo обеспечивает безболезненное и согласованное добавление, компиляцию и управление зависимостями во всей экосистеме Rust.
* Rustfmt обеспечивает единый стиль кодирования среди разработчиков.
* Rust Language Server обеспечивает интеграцию с интегрированной средой разработки (IDE) для завершения кода и встроенных сообщений об ошибках.

+
Используя эти и другие инструменты в экосистеме Rust, разработчики могут продуктивно писать код системного уровня.

Студенты::

Rust предназначен для студентов и тех, кто заинтересован в изучении системных концепций. Используя Rust, все больше людей узнают о таких темах, как разработка операционных систем. Сообщество Rust очень дружелюбно и с удовольствием отвечает на вопросы начинающих разработчиков.
+
Используя разные каналы коммуникации, в частности эту книгу, команды разработчиков Rust хотят сделать системные концепции более доступными для большего числа людей, особенно для новичков в программировании.

Компании::

Сотни компаний, больших и малых, используют Rust в производстве для решения самых разных задач. Эти задачи включают в себя инструменты командной строки, веб-сервисы, инструменты DevOps, встроенные устройства, аудио- и видеоанализ с транскодированием, криптовалюты, биоинформатику, поисковые системы, приложения Интернета вещей, машинное обучение и даже основные части веб-браузера Firefox.

Разработчики open source::

Rust предназначен для людей, которые хотят создавать язык программирования Rust, развивать сообщество, разрабатывать девелоперские инструменты и библиотеки. Мы будем рады, если вы внесете свой вклад в язык Rust.

Ценители скорости и стабильности::

Rust будет полезен людям, которые ценят в языке скорость и стабильность. Под скоростью мы подразумеваем как скорость выполнения программ, которые вы можете создавать с помощью Rust, так и скорость их написания. Проверки компилятора Rust обеспечивают стабильность за счет ключевых дополнений и рефакторинга. Это контрастирует с хрупким устаревшим кодом, написанным на языках без таких проверок, который разработчики часто опасаются модифицировать. Стремясь к абстракциям с нулевой стоимостью, функциям более высокого уровня, которые компилируются в код более низкого уровня так же быстро, как код, написанный вручную, Rust позволяет сделать безопасный код также быстрым кодом.

Язык Rust найдет поддержку у многих других пользователей; здесь упомянуты лишь ключевые группы интересантов. В целом, самая большая цель Rust — устранить компромиссы, на которые программисты шли десятилетиями, обеспечивая безопасность и производительность, скорость и эргономику. Попробуйте Rust и посмотрите, подойдут ли вам его варианты.

=== Для кого эта книга

В этой книге предполагается, что читатель имеет опыт программирования на других языках (не имеет значения каких). Для таких читателей мы постарались сделать материал книги очень доступным для понимания. Но честно предупреждаем — у нас нет возможности тратить много времени на разговоры о том, что такое программирование или как о нем думать. Для новичков в программировании эта книга будет очень трудной для изучения и будет гораздо эффективнее сначала ознакомится с обучающими материалами по введению в программирование, а потом уже вернуться к чтению книги.

=== Как использовать эту книгу

В целом, эта книга предполагает, что вы читаете ее последовательно с начала и до конца. Последующие главы основаны на концепциях предыдущих глав, а более ранние главы могут не углубляться в детали той или иной темы; обычно мы возвращаемся к ним в последующих главах.

В книге представлены два типа глав: концептуальные и проектные. В концептуальных главах обычно говорится о каком-то определенном аспекте Rust. В проектных главах мы будем вместе создавать небольшие программы, применяя то, что вы уже узнали. xref:_chapter_2[Глава 2], Глава 12 и Глава 20 являются проектными; остальные — концептуальными.

xref:_chapter_1[Глава 1] объясняет, как установить Rust, написать «Hello, world!» и использовать Cargo (менеджер пакетов Rust и инструмент сборки). xref:_chapter_2[Глава 2] представляет собой практическое введение в язык Rust. Здесь на верхнем уровне рассматриваются основные концепции, которые обрастают дополнительными подробностями в следующих главах книги. Если вы хотите сразу же попробовать Rust в деле, xref:_chapter_2[Глава 2] — самое подходящее место для этого. При первом чтении можно пропустить xref:_chapter_3[Главу 3], в которой рассматриваются общие для большинства языков программирования возможности Rust, и сразу перейти к xref:_chapter_4[Главе 4], чтобы узнать о системе владения Rust. Однако, если вы предпочитаете изучать каждую деталь, прежде чем переходить к следующей, то можете пропустить xref:_chapter_2[Главу 2] и сразу перейти к xref:_chapter_3[Главе 3], а потом вернуться к xref:_chapter_2[Главе 2], когда захотите поработать над проектом, применяя изученный материал.

В xref:_chapter_5[Главе 5] обсуждаются структуры и методы, в xref:_chapter_6[Главе 6] — перечисления, выражения `match` и конструкция управления потоком выполнения `if let`. Структуры и перечисления используются в Rust для создания пользовательских типов.

В Главе 7 вы узнаете о модульной системе Rust и о правилах конфиденциальности для организации вашего кода и формирования общедоступного API (Application Programming Interface). В Главе 8 обсуждаются некоторые общие структуры данных коллекций, предоставляемые стандартной библиотекой, такие как векторы, строки и хэш-отображения (hash map). Глава 9 исследует философию и методы обработки ошибок Rust.

В Главе 10 рассматриваются обобщенные типы, трейты и времена жизни, что откроет возможность писать код, применимый к сразу к нескольким различным типам. Глава 11 посвящена тестированию, которое даже с учетом гарантий безопасности Rust необходимо для обеспечения правильности логики вашей программы. В Главе 12 мы напишем собственную реализацию подмножества функций утилиты командной строки `grep` для поиска заданного текста в файлах, для чего применим многие концепции из предыдущих главах.

Глава 13 посвящена замыканиям и итераторам: функциям Rust, пришедшим из функциональных языков программирования. В Главе 14 мы более подробно рассмотрим Cargo и поговорим о лучших практиках совместного использования ваших библиотек в других проектах. В Главе 15 обсуждаются умные указатели, предоставляемые стандартной библиотекой, и трейты для обеспечения функциональности этих указателей.

В Главе 16 рассмотрим различные модели параллельного программирования и поговорим о том, как Rust помогает безбоязненно создавать многопоточный код. В Главе 17 показано, как идиомы Rust сопоставляются с наиболее общими принципами объектно-ориентированного программирования.

Глава 18 представляет собой справочник по работе с шаблонами и сопоставлению с шаблонами (pattern matching), которые являются мощным способом выражения идей в программах на Rust. Глава 19 содержит множество интересных тем, включая небезопасный Rust, макросы и многое другое о временах жизни, трейтах, типах, функциях и замыканиях.

В Главе 20 мы реализуем низкоуровневый многопоточный веб-сервер!

Наконец, в приложениях содержится полезная информация о языке в более справочном формате. Приложение A описывает ключевые слова Rust, Приложение B — операторы и символы Rust, Приложение C — производные трейты, предоставленные в стандартной библиотеке, Приложение D — некоторые полезные инструменты разработки, а Приложение E — версии Rust.

Не существует неправильного способа прочесть эту книгу: если вы хотите что-то пропустить, делайте это! Возможно, придется вернуться к предыдущим главам, если вы запутались. Делайте все, что посчитаете правильным для вас.

Важной частью процесса обучения Rust является анализ сообщений об ошибках, которые отображает компилятор: в них даются подсказки для написания корректного кода. Мы предоставим множество примеров ошибочного кода вместе с сообщениями об ошибках его компиляции. Предупреждаем, что если вы введете и запустите случайный пример, он может не скомпилироваться! Скорее всего вы пытаетесь запустить код, который на самом деле приведен для демонстрации какой-то ошибочной ситуации Rust; чтобы убедиться в этом, просто прочтите поясняющий текст. Не переживайте, в большинстве случаев будет приведена правильная версия ошибочного кода.

=== Исходный код

Исходные файлы программ, приведенных в книге, выложены на GitHub по ссылке _https://github.com/rust-lang/book/tree/main/src_
